services:
  postgres:
    build:
      context: ./docker_postgres_database/
      dockerfile: Dockerfile
    container_name: postgres_collections-${VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker_postgres_database/data:/var/lib/postgresql/data
    networks:
      - internal

  postgres_interface:
    build:
      context: ./docker_database_interface/
      dockerfile: Dockerfile
    container_name: postgres_interface-${VERSION}
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - internal
      - external

  postgres_display:
    build:
      context: ./docker_display_database/
      dockerfile: Dockerfile
    container_name: postgres_display-${VERSION}
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - postgres_interface
    networks:
      - internal
      - external

networks:
  internal:
    internal: true # Create an internal-only network.
  external:
    driver: bridge
